"""Stage 4: train our link failure predictor, a Random Forest plus XGBoost ensemble.

This script was missing from the repository for a while, which meant the shipped
model files could not be regenerated by anything in the tree. It is back, and it
now writes a manifest recording exactly which artifacts it produced, from which
dataset, under which split.

Two correctness changes over the original version.

1. The blend weights are chosen on a validation split carved out of the training
   runs. The original computed them from test set AUC, which is model selection
   on the test set. It is only one scalar, but it is leakage and it costs nothing
   to remove.

2. The two ensemble members are verified to be genuinely different models before
   anything is written. Previously the two artifact files could end up byte
   identical, and because the blend is 0.6 * p + 0.4 * p = p, nothing failed. A
   silent no op ensemble is worse than a crash.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    average_precision_score,
    brier_score_loss,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "config"))
from bootstrap import setup_paths  # noqa: E402

ROOT = setup_paths()

from config_loader import get_config  # noqa: E402
from label_utils import add_link_failure_labels, drop_label_aux_columns, label_diagnostics  # noqa: E402
from schema import FEATURES, TARGET, assert_columns  # noqa: E402
from splits import assert_no_row_overlap, make_run_split, split_frame  # noqa: E402

CFG = get_config()
MODELS_DIR = ROOT / "results" / "models"
DEFAULT_DATASET = ROOT / "data" / "processed" / "paper_featured_dataset.csv"

RF_PATH = MODELS_DIR / "random_forest.pkl"
XGB_PATH = MODELS_DIR / "xgboost_model.pkl"
SCALER_PATH = MODELS_DIR / "scaler.pkl"
WEIGHTS_PATH = MODELS_DIR / "ensemble_weights.pkl"
SCHEMA_PATH = MODELS_DIR / "predictor_schema.json"
METRICS_PATH = ROOT / "results" / "predictor_metrics.json"


class EnsembleIntegrityError(RuntimeError):
    pass


def _classification_report(y_true, proba, threshold: float = 0.5) -> dict:
    y_true = np.asarray(y_true, dtype=int)
    proba = np.asarray(proba, dtype=float)
    pred = (proba >= threshold).astype(int)
    single_class = len(np.unique(y_true)) < 2
    tn, fp, fn, tp = (
        confusion_matrix(y_true, pred, labels=[0, 1]).ravel()
        if len(y_true)
        else (0, 0, 0, 0)
    )
    return {
        "n": int(len(y_true)),
        "positive_rate": float(y_true.mean()) if len(y_true) else float("nan"),
        "roc_auc": float("nan") if single_class else float(roc_auc_score(y_true, proba)),
        "average_precision": float("nan") if single_class else float(average_precision_score(y_true, proba)),
        "precision": float(precision_score(y_true, pred, zero_division=0)),
        "recall": float(recall_score(y_true, pred, zero_division=0)),
        "f1": float(f1_score(y_true, pred, zero_division=0)),
        "brier": float(brier_score_loss(y_true, proba)) if len(y_true) else float("nan"),
        "confusion_matrix": {"tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp)},
        "threshold": float(threshold),
    }


def verify_distinct_members(rf, xgb_model, X_probe: np.ndarray) -> dict:
    """Refuse to ship an ensemble whose members are the same model.

    Checks three independent things: the classes differ, the objects are not the
    same instance, and the predictions actually disagree somewhere. The last one
    is the check that would have caught the duplicated artifact, because two
    copies of one forest pass any type check you care to write.
    """
    if type(rf) is type(xgb_model):
        raise EnsembleIntegrityError(
            f"both ensemble members are {type(rf).__name__}; expected a "
            "RandomForestClassifier and an XGBClassifier"
        )
    if rf is xgb_model:
        raise EnsembleIntegrityError("both ensemble members are the same object")

    p_rf = rf.predict_proba(X_probe)[:, 1]
    p_xgb = xgb_model.predict_proba(X_probe)[:, 1]
    max_abs_diff = float(np.max(np.abs(p_rf - p_xgb))) if len(X_probe) else 0.0
    if max_abs_diff < 1e-9:
        raise EnsembleIntegrityError(
            "ensemble members produce identical probabilities on every probe row; "
            "the blend would be a no op"
        )
    return {
        "rf_class": type(rf).__name__,
        "xgb_class": type(xgb_model).__name__,
        "max_abs_probability_difference": max_abs_diff,
        "mean_abs_probability_difference": float(np.mean(np.abs(p_rf - p_xgb))),
    }


def train(
    dataset_path: str | Path = DEFAULT_DATASET,
    smoke: bool = False,
    seed: int = None,
    test_run_count: int = None,
    val_run_count: int = None,
) -> dict:
    seed = CFG.random_seed if seed is None else seed
    tr_cfg = CFG.training
    sm = CFG.smoke
    test_run_count = (sm["test_run_count"] if smoke else CFG.test_run_count) if test_run_count is None else test_run_count
    val_run_count = (sm["val_run_count"] if smoke else CFG.val_run_count) if val_run_count is None else val_run_count

    df = pd.read_csv(dataset_path)
    assert_columns(df, FEATURES + ["run_id", "node_id", "time"], "train_predictor")
    df = add_link_failure_labels(df)
    df = drop_label_aux_columns(df)

    run_ids = sorted(df["run_id"].unique().astype(int).tolist())
    split = make_run_split(run_ids, seed=seed, test_run_count=test_run_count, val_run_count=val_run_count)
    train_df, val_df, test_df = split_frame(df, split)
    assert_no_row_overlap(train_df, test_df)
    if len(val_df):
        assert_no_row_overlap(val_df, test_df)

    X_train = train_df[FEATURES].to_numpy(dtype=float)
    y_train = train_df[TARGET].to_numpy(dtype=int)
    X_val = val_df[FEATURES].to_numpy(dtype=float) if len(val_df) else X_train[:0]
    y_val = val_df[TARGET].to_numpy(dtype=int) if len(val_df) else y_train[:0]
    X_test = test_df[FEATURES].to_numpy(dtype=float)
    y_test = test_df[TARGET].to_numpy(dtype=int)

    # Fitted on training rows only, then applied to val and test unchanged.
    scaler = StandardScaler().fit(X_train)
    Xtr, Xva, Xte = scaler.transform(X_train), scaler.transform(X_val), scaler.transform(X_test)

    rf = RandomForestClassifier(
        n_estimators=int(sm["rf_estimators"] if smoke else tr_cfg["rf_estimators"]),
        max_depth=int(sm["rf_max_depth"] if smoke else tr_cfg["rf_max_depth"]),
        random_state=seed,
        n_jobs=-1,
        class_weight="balanced_subsample",
    )
    rf.fit(Xtr, y_train)

    pos = max(1, int((y_train == 1).sum()))
    neg = max(1, int((y_train == 0).sum()))
    xgb_model = XGBClassifier(
        n_estimators=int(sm["xgb_estimators"] if smoke else tr_cfg["xgb_estimators"]),
        max_depth=int(sm["xgb_max_depth"] if smoke else tr_cfg["xgb_max_depth"]),
        learning_rate=float(tr_cfg["xgb_learning_rate"]),
        subsample=0.8,
        colsample_bytree=0.8,
        reg_lambda=1.0,
        scale_pos_weight=neg / pos,
        random_state=seed,
        n_jobs=-1,
        eval_metric="auc",
        # Early stopping on the validation runs, never on test.
        early_stopping_rounds=(
            None if (smoke or len(X_val) == 0) else int(tr_cfg["xgb_early_stopping_rounds"])
        ),
    )
    if len(X_val) and not smoke:
        xgb_model.fit(Xtr, y_train, eval_set=[(Xva, y_val)], verbose=False)
    else:
        xgb_model.fit(Xtr, y_train, verbose=False)

    integrity = verify_distinct_members(rf, xgb_model, Xte[:512] if len(Xte) else Xtr[:512])

    # Blend weights from validation AUC. Falls back to an even split when there
    # is no validation data, which only happens in smoke runs.
    def _auc(model, X, y) -> float:
        if len(y) == 0 or len(np.unique(y)) < 2:
            return float("nan")
        return float(roc_auc_score(y, model.predict_proba(X)[:, 1]))

    rf_val_auc = _auc(rf, Xva, y_val)
    xgb_val_auc = _auc(xgb_model, Xva, y_val)
    if np.isnan(rf_val_auc) or np.isnan(xgb_val_auc) or (rf_val_auc + xgb_val_auc) <= 0:
        w_rf, w_xgb, weight_source = 0.5, 0.5, "equal_fallback_no_validation_data"
    else:
        w_rf = float(rf_val_auc / (rf_val_auc + xgb_val_auc))
        w_xgb = float(1.0 - w_rf)
        weight_source = "validation_auc"

    p_test = w_rf * rf.predict_proba(Xte)[:, 1] + w_xgb * xgb_model.predict_proba(Xte)[:, 1]

    metrics = {
        "dataset": str(dataset_path),
        "smoke": bool(smoke),
        "seed": int(seed),
        "split": split.as_dict(),
        "rows": {"train": int(len(y_train)), "val": int(len(y_val)), "test": int(len(y_test))},
        "features": FEATURES,
        "label_diagnostics": label_diagnostics(df),
        "ensemble_weights": {"rf": w_rf, "xgb": w_xgb, "source": weight_source},
        "validation_auc": {"rf": rf_val_auc, "xgb": xgb_val_auc},
        "integrity": integrity,
        "test": {
            "rf": _classification_report(y_test, rf.predict_proba(Xte)[:, 1]),
            "xgb": _classification_report(y_test, xgb_model.predict_proba(Xte)[:, 1]),
            "ensemble": _classification_report(y_test, p_test),
        },
        "feature_importance_rf": {
            f: float(v) for f, v in sorted(
                zip(FEATURES, rf.feature_importances_), key=lambda kv: -kv[1]
            )
        },
    }

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(rf, RF_PATH)
    joblib.dump(xgb_model, XGB_PATH)
    joblib.dump(scaler, SCALER_PATH)
    joblib.dump({"rf": w_rf, "xgb": w_xgb}, WEIGHTS_PATH)
    with open(SCHEMA_PATH, "w", encoding="utf-8") as f:
        json.dump(
            {
                "features": FEATURES,
                "n_features": len(FEATURES),
                "target": TARGET,
                "scaler": "StandardScaler fitted on training runs only",
                "split": split.as_dict(),
                "seed": int(seed),
                "artifacts": {
                    "rf": RF_PATH.name,
                    "xgb": XGB_PATH.name,
                    "scaler": SCALER_PATH.name,
                    "weights": WEIGHTS_PATH.name,
                },
            },
            f,
            indent=2,
        )
    METRICS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(METRICS_PATH, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)

    # Re-read from disk and re-verify, so a bad serialisation cannot slip through.
    reloaded_rf = joblib.load(RF_PATH)
    reloaded_xgb = joblib.load(XGB_PATH)
    verify_distinct_members(reloaded_rf, reloaded_xgb, Xte[:256] if len(Xte) else Xtr[:256])

    return metrics


def main() -> None:
    parser = argparse.ArgumentParser(description="Train the RF + XGBoost link failure predictor.")
    parser.add_argument("--dataset", default=str(DEFAULT_DATASET))
    parser.add_argument("--smoke", action="store_true", help="tiny, fast configuration for CI")
    parser.add_argument("--seed", type=int, default=CFG.random_seed)
    parser.add_argument("--test-run-count", type=int, default=None)
    parser.add_argument("--val-run-count", type=int, default=None)
    args = parser.parse_args()

    m = train(
        dataset_path=args.dataset,
        smoke=args.smoke,
        seed=args.seed,
        test_run_count=args.test_run_count,
        val_run_count=args.val_run_count,
    )
    print(f"[train_predictor] split -> train={len(m['split']['train_runs'])} runs, "
          f"val={len(m['split']['val_runs'])} runs, test={len(m['split']['test_runs'])} runs")
    print(f"[train_predictor] ensemble members verified distinct "
          f"({m['integrity']['rf_class']} vs {m['integrity']['xgb_class']}, "
          f"max prob diff {m['integrity']['max_abs_probability_difference']:.4f})")
    print(f"[train_predictor] blend weights {m['ensemble_weights']} ")
    for name in ("rf", "xgb", "ensemble"):
        r = m["test"][name]
        print(f"[train_predictor] test {name:9s} auc={r['roc_auc']:.4f} ap={r['average_precision']:.4f} "
              f"f1={r['f1']:.4f} brier={r['brier']:.4f}")
    print(f"[train_predictor] metrics written to {METRICS_PATH}")


if __name__ == "__main__":
    main()
